apiVersion: v1
kind: Service
metadata:
  name: {{ include "eaos.gateway.fullname" . }}
  labels:
    {{- include "eaos.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if and .Values.mesh.enabled .Values.mesh.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.mesh.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "eaos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
